#!/usr/bin/env bash
# generate-recipe.sh — scaffold a new terminal-demo recipe from a template.
#
# A recipe is a self-contained shell script that: creates/uses a throwaway
# workdir, prints a printf "beat" label before each real command, sleeps at
# human cadence, then runs REAL tools (no mocked output). This generator
# writes that skeleton so a new realistic demo takes minutes, not a rewrite.
#
# Usage:
#   ./generate-recipe.sh <recipe-name> "Label 1|||command 1" "Label 2|||command 2" ...
#
# Example:
#   ./generate-recipe.sh db-migrate \
#     "Real schema, one pending migration|||npx prisma migrate status" \
#     "Applying it for real|||npx prisma migrate deploy" \
#     "Confirm the new table exists|||npx prisma db pull --print"
#
# Each "Label|||command" pair becomes one beat: a printf label, a short
# sleep, then the literal command run in the recipe's workdir. Edit the
# generated file afterward to add real setup (package.json, fixture files,
# a genuine bug/fix pair) — this only scaffolds the beat structure and the
# workdir/help boilerplate every recipe in this directory shares.
set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <recipe-name> \"Label|||command\" [\"Label|||command\" ...]" >&2
  echo "See generate-recipe.sh header for a worked example." >&2
  exit 1
fi

NAME="$1"
shift

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/${NAME}.sh"

if [ -e "$OUT" ]; then
  echo "Refusing to overwrite existing recipe: $OUT" >&2
  exit 1
fi

{
  printf '#!/usr/bin/env bash\n'
  printf '# %s.sh — generated by generate-recipe.sh.\n' "$NAME"
  printf '# Fill in real tool calls below; keep every "input" and "output" genuine.\n'
  printf '#\n'
  printf '# Usage:\n'
  printf '#   ./%s.sh [workdir]\n' "$NAME"
  printf 'set -euo pipefail\n'
  printf 'export FORCE_COLOR=1\n'
  printf '\n'
  printf 'WORKDIR="${1:-$(mktemp -d -t spectra-%s)}"\n' "$NAME"
  printf 'mkdir -p "$WORKDIR"\n'
  printf 'cd "$WORKDIR"\n'
  printf '\n'
  printf 'beat() {\n'
  printf "  printf '\\\\n\\\\033[1;36m▸ %%s\\\\033[0m\\\\n' \"\$1\"\n"
  printf '  sleep "${2:-0.9}"\n'
  printf '}\n'

  while [ "$#" -gt 0 ]; do
    entry="$1"
    shift
    label="${entry%%|||*}"
    cmd="${entry#*|||}"
    printf '\n'
    printf 'beat %q 0.7\n' "$label"
    printf '%s\n' "$cmd"
  done

  printf '\n'
  printf 'beat "Done. Workdir: $WORKDIR" 1.0\n'
} > "$OUT"

chmod +x "$OUT"
echo "Wrote $OUT"
echo "Edit it to wire in real setup files, then run: $OUT"
